version: '3.8'

services:

  frontend:
    build: .
    volumes:
      - build_folder:/build
    command: serve -s build -l 8080

  nginx:
    build: ./nginx
    volumes:
      - build_folder:/var/www
    ports:
      - 80:8080
    depends_on:
      - frontend

volumes:
  build_folder: